# Copyright 2026 Intelligent Robotics Lab
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Build a whole `--package` colcon package tree for a navmap_gis_tool run.

Mirrors src/urjc-excavation-world's structure and file conventions exactly
(worlds/*.world, models/<name>/{model.sdf,model.config,meshes/}, maps/,
launch/*.launch.py, env-hooks/*.dsv.in) so the generated package plugs into
this workspace the same way that reference world package does -- see
easynav_gis_tool.md for why this structure was chosen. `--package` is the
exact ROS package name the user wants (e.g. "urjc_excavation_world"); the
shorter `name` used for the model directory and the world/mesh/map file
basenames is that package name with a trailing "_world" stripped, matching
how urjc-excavation-world itself is named ("urjc_excavation_world" package,
"urjc_excavation" model/mesh basename).

Scaffold files (package.xml, CMakeLists.txt, worlds/, models/, launch/,
env-hooks/, README.md) are always (re)written. `maps/` is left to the
caller (pcd_writer / the pointcloud_to_navmap tool): re-running with only
one of --gazebo/--navmap must not clobber files the other flag already
produced in a previous, separate invocation into the same --output-dir.
"""

from dataclasses import dataclass
from pathlib import Path


def _render(template: str, **kwargs) -> str:
    out = template
    for key, value in kwargs.items():
        out = out.replace(f'__{key.upper()}__', str(value))
    return out


@dataclass
class WorldPaths:
    """Resolved paths inside a generated `--package` package."""

    package_name: str
    name: str
    root: Path
    maps_dir: Path
    models_dir: Path
    model_dir: Path
    meshes_dir: Path
    worlds_dir: Path
    launch_dir: Path
    env_hooks_dir: Path

    @property
    def pcd_path(self) -> Path:
        """Path of the point cloud consumed/produced for --navmap."""
        return self.maps_dir / f'{self.name}.pcd'

    @property
    def navmap_path(self) -> Path:
        """Path of the generated .navmap file."""
        return self.maps_dir / f'{self.name}.navmap'

    @property
    def colors_csv_path(self) -> Path:
        """Path of the per-point RGB sidecar for the point cloud (see pcd_writer.py)."""
        return self.maps_dir / f'{self.name}_colors.csv'

    @property
    def world_path(self) -> Path:
        """Path of the generated .world SDF file."""
        return self.worlds_dir / f'{self.name}.world'

    @property
    def dae_path(self) -> Path:
        """Path of the generated visual mesh."""
        return self.meshes_dir / f'{self.name}.dae'

    @property
    def stl_path(self) -> Path:
        """Path of the generated collision mesh."""
        return self.meshes_dir / f'{self.name}.stl'

    @property
    def texture_path(self) -> Path:
        """Path of the generated diffuse texture."""
        return self.meshes_dir / f'{self.name}_texture.png'


def short_name_for(package_name: str) -> str:
    """
    Derive the model/mesh/world basename from a package name.

    Strips a trailing "_world" (e.g. "urjc_excavation_world" -> "urjc_excavation"),
    matching src/urjc-excavation-world's own naming; packages not following
    that convention are used as-is.
    """
    suffix = '_world'
    if package_name.endswith(suffix) and len(package_name) > len(suffix):
        return package_name[:-len(suffix)]
    return package_name


def world_paths(output_dir, package_name: str) -> WorldPaths:
    """Resolve every path inside the `<output_dir>` package for `package_name`."""
    name = short_name_for(package_name)
    root = Path(output_dir)
    models_dir = root / 'models'
    model_dir = models_dir / name
    return WorldPaths(
        package_name=package_name,
        name=name,
        root=root,
        maps_dir=root / 'maps',
        models_dir=models_dir,
        model_dir=model_dir,
        meshes_dir=model_dir / 'meshes',
        worlds_dir=root / 'worlds',
        launch_dir=root / 'launch',
        env_hooks_dir=root / 'env-hooks',
    )


_PACKAGE_XML = """<?xml version="1.0"?>
<package format="2">
  <name>__PACKAGE__</name>
  <version>1.0.0</version>
  <description>
    __PACKAGE__ for Gazebo simulations, generated by navmap_tools'
    navmap_gis_tool from GPS center (__LAT__, __LON__) and size __SIZE__ m.
  </description>
  <license>Apache 2.0</license>
  <author email="fmrico@gmail.com">Generated by navmap_tools (navmap_gis_tool)</author>
  <maintainer email="fmrico@gmail.com">Generated by navmap_tools (navmap_gis_tool)</maintainer>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ros_gz</exec_depend>
  <exec_depend>gz_sim_vendor</exec_depend>
  <exec_depend>gz_plugin_vendor</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <gazebo_ros gazebo_model_path="${prefix}/models"/>
    <gazebo_ros gazebo_media_path="${prefix}/worlds"/>
  </export>
</package>
"""

_CMAKELISTS = """cmake_minimum_required(VERSION 3.5)
project(__PACKAGE__)

find_package(ros_gz_sim REQUIRED)
find_package(ament_cmake_ros REQUIRED)

install(DIRECTORY launch maps models worlds
    DESTINATION share/${PROJECT_NAME}
)

ament_environment_hooks("${CMAKE_CURRENT_SOURCE_DIR}/env-hooks/__PACKAGE__.dsv.in")

ament_export_dependencies(ros_gz_sim)

ament_package()
"""

_ENV_HOOK = """set;GZ_VERSION;@GZ_VERSION@
prepend-non-duplicate;GZ_SIM_RESOURCE_PATH;@CMAKE_INSTALL_PREFIX@/share/@PROJECT_NAME@/models
prepend-non-duplicate;GZ_SIM_RESOURCE_PATH;@CMAKE_INSTALL_PREFIX@/share/@PROJECT_NAME@/worlds
prepend-non-duplicate;GZ_SIM_SYSTEM_PLUGIN_PATH;@CMAKE_INSTALL_PREFIX@/lib

prepend-non-duplicate;LD_LIBRARY_PATH;@CMAKE_INSTALL_PREFIX@/lib
"""

_MODEL_CONFIG = """<?xml version="1.0"?>

<model>
  <name>__NAME__</name>
  <version>1.0</version>
  <sdf version="1.6">model.sdf</sdf>

  <author>
    <name>Generated by navmap_tools (navmap_gis_tool)</name>
    <email>fmrico@gmail.com</email>
  </author>

  <description>
    Terrain generated from GIS data (GPS center __LAT__, __LON__; size __SIZE__ m;
    DEM: Copernicus GLO-30; imagery: __IMAGERY_DESC__).
  </description>
</model>
"""

_MODEL_SDF = """<?xml version="1.0" ?>
<sdf version="1.6">
  <model name="ground_plane">
    <static>true</static>
    <link name="ground_plane_link">
      <collision name="collision">
        <geometry>
          <mesh>
            <uri>model://__NAME__/meshes/__NAME__.stl</uri>
          </mesh>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>0.9000000</mu>
              <mu2>0.1000000</mu2>
              <fdir1>0.000000 0.000000 1.000000</fdir1>
            </ode>
          </friction>
          <bounce>
            <restitution_coefficient>0.000000</restitution_coefficient>
            <threshold>100000.000000</threshold>
          </bounce>
          <contact>
            <ode>
              <soft_cfm>9.000000</soft_cfm>
              <soft_erp>9.000000</soft_erp>
              <kp>10000.000000</kp>
              <kd>1.000000</kd>
              <max_vel>100.000000</max_vel>
              <min_depth>0.001000</min_depth>
            </ode>
          </contact>
        </surface>
      </collision>
      <visual name="visual">
        <geometry>
          <mesh>
            <uri>model://__NAME__/meshes/__NAME__.dae</uri>
          </mesh>
        </geometry>
      </visual>
    </link>
  </model>
</sdf>
"""

_WORLD_SDF = """<?xml version="1.0"?>
<sdf version="1.6">
    <world name='__PACKAGE__'>

        <physics name="5ms" type="ignored">
            <max_step_size>0.005</max_step_size>
            <real_time_factor>1.0</real_time_factor>
        </physics>

        <plugin entity_name="*" entity_type="world"
            filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
        <plugin entity_name="*" entity_type="world"
            filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
        <plugin entity_name="*" entity_type="world"
            filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
        <plugin entity_name="*" entity_type="world"
            filename="gz-sim-contact-system" name="gz::sim::systems::Contact"/>
        <plugin entity_name="*" entity_type="world"
            filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>
        <plugin entity_name="*" entity_type="world"
            filename="gz-sim-air-pressure-system" name="gz::sim::systems::AirPressure"/>
        <plugin entity_name="*" entity_type="world"
            filename="gz-sim-air-speed-system" name="gz::sim::systems::AirSpeed"/>
        <plugin entity_name="*" entity_type="world"
            filename="gz-sim-apply-link-wrench-system" name="gz::sim::systems::ApplyLinkWrench"/>
        <plugin entity_name="*" entity_type="world"
            filename="gz-sim-navsat-system" name="gz::sim::systems::NavSat"/>
        <plugin entity_name="*" entity_type="world"
            filename="gz-sim-magnetometer-system" name="gz::sim::systems::Magnetometer"/>
        <plugin entity_name="*" entity_type="world"
            filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
            <render_engine>ogre2</render_engine>
        </plugin>

        <!-- Anchors the world's local ENU origin (0,0,0) to the real-world GPS
             center this terrain was generated from. -->
        <spherical_coordinates>
            <surface_model>EARTH_WGS84</surface_model>
            <world_frame_orientation>ENU</world_frame_orientation>
            <latitude_deg>__LAT__</latitude_deg>
            <longitude_deg>__LON__</longitude_deg>
            <elevation>__ELEVATION__</elevation>
            <heading_deg>0</heading_deg>
        </spherical_coordinates>

        <gravity>0.0 0.0 -9.8</gravity>

        <scene>
            <ambient>0.4 0.4 0.4 1</ambient>
            <background>0.7 0.7 0.7 1</background>
            <shadows>false</shadows>
            <grid>false</grid>
            <origin_visual>false</origin_visual>
        </scene>

        <light name='sun' type='directional'>
            <cast_shadows>0</cast_shadows>
            <pose>0 0 10000 0 0 0</pose>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.2 0.2 0.2 1</specular>
            <attenuation>
                <range>1000</range>
                <constant>0.9</constant>
                <linear>0.01</linear>
                <quadratic>0.001</quadratic>
            </attenuation>
            <direction>-0.5 0.1 -0.9</direction>
        </light>

        <include>
            <uri>model://__NAME__</uri>
        </include>
    </world>
</sdf>
"""

_LAUNCH_PY = '''# Copyright 2026 Intelligent Robotics Lab
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Launch __PACKAGE__ standalone in Gazebo (gz sim -r -v4), no ROS robot."""

import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, ExecuteProcess, SetEnvironmentVariable
from launch.substitutions import LaunchConfiguration


def generate_launch_description():
    world_file_name = '__NAME__.world'
    package_dir = get_package_share_directory('__PACKAGE__')
    world = LaunchConfiguration('world')

    model_path = os.path.join(package_dir, 'models')

    gazebo = ExecuteProcess(
        cmd=['gz', 'sim', '-r', '-v4', world], output='screen')

    return LaunchDescription([
        SetEnvironmentVariable('GZ_SIM_RESOURCE_PATH', model_path),
        DeclareLaunchArgument(
            'world',
            default_value=[os.path.join(package_dir, 'worlds', world_file_name), ''],
            description='SDF world file'),
        DeclareLaunchArgument(name='use_sim_time', default_value='true'),
        gazebo,
    ])


if __name__ == '__main__':
    generate_launch_description()
'''

_README = """# __PACKAGE__

Gazebo (gz-sim) world generated by `navmap_tools`' `navmap_gis_tool` from
real-world GIS data:

* Center: __LAT__, __LON__
* Size: __SIZE__ m x __SIZE__ m
* Elevation source: Copernicus DEM GLO-30 (~30 m, public AWS Open Data, no API key)
* Imagery source: __IMAGERY_DESC__

Attribution: contains modified Copernicus DEM data -- see
https://spacedata.copernicus.eu/ for its terms. __IMAGERY_ATTRIBUTION__

## Load directly into Gazebo (without ROS)

```bash
export GZ_SIM_RESOURCE_PATH=`pwd`/models:`pwd`/worlds
gz sim worlds/__NAME__.world
```

## ROS launch (standalone, no robot)

```bash
colcon build --symlink-install --packages-select __PACKAGE__
source install/setup.bash
ros2 launch __PACKAGE__ __NAME__.launch.py
```

## NavMap

If generated with `--navmap`, `maps/__NAME__.pcd` and `maps/__NAME__.navmap`
sit alongside this world and share the exact same local-ENU origin (this
world's GPS center), so they line up with the terrain above even though they
may have been produced in a separate `navmap_gis_tool` run. Publish it for
RViz2 with:

```bash
ros2 run navmap_tools navmap_publisher --input maps/__NAME__.navmap
```
"""


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def scaffold_world_package(
    output_dir,
    package_name: str,
    center_lat: float,
    center_lon: float,
    size_m: float,
    elevation_amsl: float,
    imagery_desc: str,
    imagery_attribution: str = '',
) -> WorldPaths:
    """Create/update the `--package` package tree; returns its resolved paths."""
    if not package_name or not package_name.replace('_', '').isalnum():
        raise ValueError(
            f'package name must be a valid ROS package identifier: {package_name!r}')

    paths = world_paths(output_dir, package_name)
    paths.meshes_dir.mkdir(parents=True, exist_ok=True)
    paths.maps_dir.mkdir(parents=True, exist_ok=True)
    paths.worlds_dir.mkdir(parents=True, exist_ok=True)
    paths.launch_dir.mkdir(parents=True, exist_ok=True)
    paths.env_hooks_dir.mkdir(parents=True, exist_ok=True)

    kwargs = {
        'package': package_name, 'name': paths.name, 'lat': center_lat, 'lon': center_lon,
        'size': size_m, 'elevation': elevation_amsl, 'imagery_desc': imagery_desc,
        'imagery_attribution': imagery_attribution,
    }

    _write(paths.root / 'package.xml', _render(_PACKAGE_XML, **kwargs))
    _write(paths.root / 'CMakeLists.txt', _render(_CMAKELISTS, **kwargs))
    _write(paths.env_hooks_dir / f'{package_name}.dsv.in', _ENV_HOOK)
    _write(paths.model_dir / 'model.config', _render(_MODEL_CONFIG, **kwargs))
    _write(paths.model_dir / 'model.sdf', _render(_MODEL_SDF, **kwargs))
    _write(paths.world_path, _render(_WORLD_SDF, **kwargs))
    _write(paths.launch_dir / f'{paths.name}.launch.py', _render(_LAUNCH_PY, **kwargs))
    _write(paths.root / 'README.md', _render(_README, **kwargs))

    return paths
